services:
    snac:
        build: ./snac2
        image: snac
        container_name: snac
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        volumes:
            - ./data:/data/
            - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
        entrypoint: ["/bin/sh", "/usr/local/bin/entrypoint.sh"]
        networks:
          - nginx

networks:
  nginx:
    external: true
    name: nginx

